#!/bin/sh

if [ $# -ne 1 ]; then
    NEWPATH=$PWD
else
    NEWPATH=$1
fi

/usr/bin/osascript <<-EOF
activate application "Terminal"
tell application "System Events"
    keystroke "t" using {command down}
end tell
tell application "Terminal"
    do script "cd $NEWPATH && clear" in (selected tab of the front window)
end tell
return
EOF
